name: Build and Push to GHCR

on:
    push:
        branches:
            - main

jobs:
    docker-build-push:
        runs-on: [self-hosted, linux]

        permissions:
            contents: read
            packages: write # Needed to push to GitHub Container Registry

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set image name from repo name
              id: vars
              run: echo "IMAGE=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}" >> $GITHUB_OUTPUT

            - name: Build Docker image (app build happens in Dockerfile)
              run: |
                  docker build \
                    -t ${{ steps.vars.outputs.IMAGE }}:latest \
                    -t ${{ steps.vars.outputs.IMAGE }}:${{ github.sha }} .

            - name: Push Docker image to GHCR
              run: |
                  docker push ${{ steps.vars.outputs.IMAGE }}:latest
                  docker push ${{ steps.vars.outputs.IMAGE }}:${{ github.sha }}
