name: Build and Push Docker Image to GHCR

on:
    push:
        branches: [main]

jobs:
    build-docker:
        runs-on: [self-hosted, linux]
        outputs:
            image: ${{ steps.vars.outputs.image }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set lowercase image name
              id: vars
              run: |
                  IMAGE="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/${GITHUB_REPOSITORY##*/}"
                  echo "image=$IMAGE" >> $GITHUB_OUTPUT

            - name: Build Docker image
              run: |
                  docker build \
                    -t ${{ steps.vars.outputs.image }}:latest \
                    -t ${{ steps.vars.outputs.image }}:${{ github.sha }} .

    push-docker:
        runs-on: [self-hosted, linux]
        needs: build-docker
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Push Docker image
              run: |
                  IMAGE="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/${GITHUB_REPOSITORY##*/}"
                  docker push $IMAGE:latest
                  docker push $IMAGE:${{ github.sha }}

    run-docker:
        runs-on: [self-hosted, linux]
        needs: push-docker
        steps:
            - name: Run Docker container
              run: |
                  IMAGE="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/${GITHUB_REPOSITORY##*/}"
                  docker run -d --rm --name test-container $IMAGE:latest
